services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: jjakub542
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: