services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: jjakub542
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "jjakub542"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata: